name: odc
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=0.12.0
  - aiohttp=3.7.4
  - async-timeout=3.0.1
  - attrs=21.2.0
  - av=8.0.3
  - blas=1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.5.30
  - cachetools=4.2.2
  - certifi=2021.5.30
  - cffi=1.14.5
  - chardet=3.0.4
  - click=8.0.1
  - coverage=5.5
  - cryptography=2.9.2
  - cvxpy=1.1.7
  - cvxpy-base=1.1.7
  - cycler=0.10.0
  - cython=0.29.23
  - decorator=4.4.2
  - ecos=2.0.7.post1
  - ffmpeg=4.3.1
  - freetype=2.10.4
  - future=0.18.2
  - gmp=6.2.1
  - gnutls=3.6.13
  - google-auth=1.30.1
  - google-auth-oauthlib=0.4.1
  - grpcio=1.36.1
  - icu=67.1
  - idna=2.10
  - imageio=2.9.0
  - imageio-ffmpeg=0.4.4
  - importlib-metadata=3.10.0
  - intel-openmp=2021.2.0
  - jpeg=9d
  - kiwisolver=1.3.1
  - lame=3.100
  - ld_impl_linux-64=2.33.1
  - libblas=3.9.0
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.3.0
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libpng=1.6.37
  - libprotobuf=3.14.0
  - libstdcxx-ng=9.1.0
  - libtiff=4.0.10
  - llvm-openmp=11.1.0
  - lz4-c=1.9.2
  - markdown=3.3.4
  - matplotlib=3.3.1
  - matplotlib-base=3.3.1
  - mkl=2021.2.0
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.1
  - moviepy=1.0.1
  - multidict=5.1.0
  - ncurses=6.2
  - nettle=3.6
  - numpy=1.20.2
  - numpy-base=1.20.2
  - oauthlib=3.1.0
  - olefile=0.46
  - openh264=2.1.1
  - openssl=1.1.1k
  - osqp=0.6.1
  - pip=21.1.1
  - proglog=0.1.9
  - protobuf=3.14.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pyjwt=2.1.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - python=3.7.10
  - python-dateutil=2.8.1
  - python_abi=3.7
  - readline=8.1
  - requests=2.25.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scipy=1.6.2
  - scs=2.1.3
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.35.4
  - tbb=2021.2.0
  - tensorboard=2.5.0
  - tensorboard-plugin-wit=1.6.0
  - tk=8.6.10
  - tornado=6.1
  - tqdm=4.59.0
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - urllib3=1.26.4
  - werkzeug=1.0.1
  - wheel=0.36.2
  - x264=1!152.20180806
  - xz=5.2.5
  - yarl=1.6.3
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - pillow==8.2.0
    - torch==1.8.1
    - torchvision==0.9.1
